version: '3'

services:
  web:
    build: web
    ports:
      - '8080:8080'
    volumes:
      - ./web:/usr/src/web
      - /usr/src/web/node_modules
    command: npm run dev

  api:
    build: api
    ports:
      - '5000:5000'
    volumes:
      - ./api:/usr/src/api
      - /usr/src/api/node_modules
    command: npm run dev
